TranscriptApp.Web/Areas/Admin/Models/AddFeeSetupViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using TranscriptApp.Business;
using TranscriptApp.Model.Model;

namespace TranscriptApp.Web.Areas.Admin.Models
{
    public class AddFeeSetupViewModel
    {
        [Required]
        public int Session { get; set; }

        [Required]
        [DisplayName("Fee Type")]
        public int FeeType { get; set; }

        [Required]
        public int Amount { get; set; }

        public List<Value> GetSessions()
        {
            try
            {
                var sessionLogic = new SessionLogic();
                List<Session> Sessions = sessionLogic.GetModelsBy(sess => sess.Active);
                List<Value> Values = new List<Value>();

                if (Sessions != null && Sessions.Count > 0)
                {
                    for (int i = 0; i < Sessions.Count; i++)
                    {
                        Values.Add(new Value() { Id = Sessions[i].SessionId, ValueText = Sessions[i].SessionName });
                    }
                }
                return Values;
            }

            catch(Exception ex) { throw ex; }
        }

        public List<Value> GetFeeTypes()
        {
            try
            {
                var feeTypeLogic = new FeeTypeLogic();
                List<FeeType> FeeTypes = feeTypeLogic.GetModelsBy(ft => ft.Active);
                List<Value> Values = new List<Value>();

                if (FeeTypes != null && FeeTypes.Count > 0)
                {
                    for (int i = 0; i < FeeTypes.Count; i++)
                    {
                        Values.Add(new Value() { Id = FeeTypes[i].FeeTypeId, ValueText = FeeTypes[i].FeeTypeName });
                    }
                }
                return Values;
            }

            catch (Exception ex) { throw ex; }
        }

        public List<Value> GetFees()
        {
            try
            {
                var feeLogic = new FeeLogic();
                List<Fee> Fees = feeLogic.GetModelsBy(f => f.Active);
                List<Value> Values = new List<Value>();

                if (Fees != null && Fees.Count > 0)
                {
                    for (int i = 0; i < Fees.Count; i++)
                    {
                        Values.Add(new Value() { Id = Fees[i].FeeId, ValueText = Fees[i].Amount.ToString() });
                    }
                }
                return Values;
            }

            catch (Exception ex) { throw ex; }
        }
    }
}

TranscriptApp.Web/Areas/Admin/Models/ManageFeeSetupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TranscriptApp.Web.Areas.Admin.Models
{
    public class ManageFeeSetupViewModel
    {
        public int FeeSetupId { get; set; }

        public string FeeType { get; set; }

        public decimal Amount { get; set; }

        public string Session { get; set; }

        public bool IsActivated { get; set; }
    }
}

TranscriptApp.Web/Areas/Admin/Models/ViewTranscriptRequestsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TranscriptApp.Web.Areas.Admin.Models
{
    public class ViewTranscriptRequestsViewModel
    {
        public string FullName { get; set; }

        public string Email { get; set; }

        public string PhoneNumber { get; set; }

        public string Programme { get; set; }

        public string Gender { get; set; }

        public string Level { get; set; }

        public string Department { get; set; }

        public string FeeType { get; set; }

        public string DestinationAddress { get; set; }
    }
}

TranscriptApp.Web/Areas/Admin/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TranscriptApp.Business;
using TranscriptApp.Model.Model;
using TranscriptApp.Web.Areas.Admin.Models;

namespace TranscriptApp.Web.Areas.Admin.Controllers
{
    [Authorize]
    public class AdminHomeController : Controller
    {
        public AddFeeSetupViewModel AddFeeSetupViewModel;

        public AdminHomeController()
        {
            AddFeeSetupViewModel = new AddFeeSetupViewModel();
        }

        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult ManageFeeSetup()
        {
            var viewModel = GetFeeDetsils();

            return View(viewModel);
        }

        public JsonResult ModifyFeeDetail(int FeeDetailId, string FeeDetailStatus)
        {
            try
            {
                var FeeDetailLogic = new FeeDetailLogic();
                var FeeDetailModel = FeeDetailLogic.GetModelsBy(fee => fee.FeeDetailId == FeeDetailId).LastOrDefault();
                FeeDetailModel.Active = FeeDetailStatus.ToLower() == "true" ? false : true;

                if (FeeDetailModel != null)
                {
                    FeeDetailLogic.Modify(FeeDetailModel);
                }
                var JsonPayload = new JsonPayload() { Message = "Fee Detail Status was changed", WasSuccessFul = true };

                return Json(JsonPayload, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex) { throw ex; }
        }

        //[Authorize]
        public ActionResult AddFeeSetup()
        {
            LoadFeeSetupViewBags();
            var username=User.Identity.Name;

            return View();
        }
        
        [HttpPost]
        public ActionResult AddFeeSetup(AddFeeSetupViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var FeeDetailLogic = new FeeDetailLogic();
                    var FeeDetail = new FeeDetail()
                    {
                        Fee = new FeeLogic().GetModelsBy(fee => fee.FeeId == viewModel.Amount).LastOrDefault(),
                        FeeType = new FeeTypeLogic().GetModelsBy(ft => ft.FeeTypeId == viewModel.FeeType).LastOrDefault(),
                        Session = new SessionLogic().GetModelsBy(sess => sess.SessionId == viewModel.Session).LastOrDefault(),
                        Active = true
                    };

                    var FeeDetailReturned = FeeDetailLogic.Create(FeeDetail);

                    if (FeeDetailReturned != null)
                    {
                        LoadFeeSetupViewBags();

                        return View();
                    }
                }
                return View(viewModel);
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult ViewTranscriptRequests()
        {
            var requestLogic = new RequestLogic();
            var requestList = requestLogic.GetAll().OrderBy(req => req.DateCreated).ToList();
            List<ViewTranscriptRequestsViewModel> viewModel = new List<ViewTranscriptRequestsViewModel>();

            if (requestList != null)
            {
                for (int i = 0; i < requestList.Count(); i++)
                {
                    var model = new ViewTranscriptRequestsViewModel()
                    {
                            FullName = string.Format("{0} {1} {2}", requestList[i].Person.Surname, requestList[i].Person.FirstName, requestList[i].Person.OtherName),
                            Email = requestList[i].Person.Email,
                            Gender = requestList[i].Person.Gender.GenderName,
                            PhoneNumber = requestList[i].Person.PhoneNumber,
                            Programme = requestList[i].Programme.ProgrammeName,
                            Department = requestList[i].Department.DepartmentName,
                            Level = requestList[i].Level.LevelName,
                            FeeType = requestList[i].FeeType.FeeTypeName,
                            DestinationAddress = requestList[i].DestinationAddress
                    };

                    viewModel.Add(model);
                }
                
            }
            
            return View(viewModel);
        }

        //HELPER METHODS
        private void LoadFeeSetupViewBags()
        {
            var Sessions = AddFeeSetupViewModel.GetSessions();
            var FeeTypes = AddFeeSetupViewModel.GetFeeTypes();
            var Amounts = AddFeeSetupViewModel.GetFees();

            if (Sessions != null)
            {
                ViewBag.Sessions = Sessions;
            }
            if (FeeTypes != null)
            {
                ViewBag.FeeTypes = FeeTypes;
            }
            if (Amounts != null)
            {
                ViewBag.Amounts = Amounts;
            }
        }

        private List<ManageFeeSetupViewModel> GetFeeDetsils()
        {
            var feeDetailLogic = new FeeDetailLogic();
            var feeDetails = feeDetailLogic.GetAll().OrderBy(fd => fd.Active).ToList();
            List<ManageFeeSetupViewModel> viewModel = new List<ManageFeeSetupViewModel>();

            if (feeDetails != null && feeDetails.Count > 0)
            {
                for (int i = 0; i < feeDetails.Count; i++)
                {
                    var model = new ManageFeeSetupViewModel()
                    {
                        FeeSetupId = feeDetails[i].FeeDetailId,
                        FeeType = feeDetails[i].FeeType.FeeTypeName,
                        Amount = feeDetails[i].Fee.Amount,
                        Session = feeDetails[i].Session.SessionName,
                        IsActivated = feeDetails[i].Active
                    };

                    viewModel.Add(model);
                }
            }

            return viewModel;
        }
    }
}

TranscriptApp.Web/Areas/Admin/Views/AdminHome/AddFeeSetup.cshtml
@model TranscriptApp.Web.Areas.Admin.Models.AddFeeSetupViewModel

@{
    ViewBag.Title = "Add Fee Setup";
}

<div class="card">
    <div class="card-header">
        <h2>Add Fee Setup</h2>
    </div>
    <div class="card-body">
        @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Session, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <select name="Session" class="form-control">
                        <option value="">-- Select Session --</option>
                        @if (ViewBag.Sessions != null)
                    {
                        foreach (var Session in ViewBag.Sessions)
                        {
                            <option value="@Session.Id">@Session.ValueText</option>
                    }
                }
                    </select>
                    @*@Html.EditorFor(model => model.Session, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Session, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FeeType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <select name="FeeType" class="form-control">
                        <option value="">-- Select Fee Type --</option>
                        @if (ViewBag.FeeTypes != null)
                    {
                        foreach (var FeeType in ViewBag.FeeTypes)
                        {
                            <option value="@FeeType.Id">@FeeType.ValueText</option>
                    }
                }
                    </select>
                    @*@Html.EditorFor(model => model.FeeType, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.FeeType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <select name="Amount" class="form-control">
                        <option value="">-- Select Amount --</option>
                        @if (ViewBag.Amounts != null)
                    {
                        foreach (var Amount in ViewBag.Amounts)
                        {
                            <option value="@Amount.Id">@Amount.ValueText</option>
                    }
                }
                    </select>
                    @*@Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit" class="btn btn-info" />
                </div>
            </div>
        </div>
}
    </div>
</div>

TranscriptApp.Web/Areas/Admin/Views/AdminHome/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<style>
    .card-body {
        padding: 50px 10px !important;
    }
</style>
<div class="container">
    <div class="card">
        <div class="card-body">
            <h2 class="text-info">Welcome to Transcript Manager</h2>
        </div>
    </div>
</div>

TranscriptApp.Web/Areas/Admin/Views/AdminHome/ManageFeeSetup.cshtml
@model IEnumerable<TranscriptApp.Web.Areas.Admin.Models.ManageFeeSetupViewModel>
@{
    ViewBag.Title = "ManageFeeSetup";
}

<style>
    .default-section {
        padding: 50px 10px;
    }
</style>

<link href="~/Content/DataTables-1.10.15/media/css/jquery.dataTables.css" rel="stylesheet" />
<link href="~/Content/DataTables-1.10.15/extensions/Buttons/css/buttons.dataTables.css" rel="stylesheet" />


<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/dataTables.js"></script>
<script src="~/Content/DataTables-1.10.15/media/js/jquery.dataTables.js"></script>
<script src="~/Content/DataTables-1.10.15/extensions/Buttons/js/dataTables.buttons.js"></script>
<script src="~/Content/DataTables-1.10.15/extensions/Buttons/js/buttons.colVis.js"></script>
<script src="~/Content/DataTables-1.10.15/extensions/Responsive/js/dataTables.responsive.js"></script>
<script src="~/Content/DataTables-1.10.15/buttons.flash.min.js"></script>
<script src="~/Content/DataTables-1.10.15/buttons.html5.min.js"></script>
<script src="~/Content/DataTables-1.10.15/buttons.print.min.js"></script>
<script src="~/Content/DataTables-1.10.15/jszip.min.js"></script>
<script src="~/Content/DataTables-1.10.15/pdfmake.min.js"></script>
<script src="~/Content/DataTables-1.10.15/vfs_fonts.js"></script>


<script type="text/javascript">
    let jqXHRData;
    let jqueryVersion = $.noConflict(true);
    jqueryVersion(document).ready(() => {
        jqueryVersion("#myTable").DataTable({
            dom: 'Bfrtip',
            ordering: true,
            buttons: [
                {
                    extend: 'copy',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'csv',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'excel',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'pdf',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'print',
                    exportOptions: {
                        columns: ':visible'
                    }


                }, , 'colvis'
            ]
        });

    });
</script>

@if (Model != null && Model.Count() > 0)
{
    <div class="card">
        <div class="card-header">
            <h2 class="text-info">Manage Fee Setup</h2>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-hover table-striped" id="myTable">
            <thead>
                <tr>
                    <th>SN</th>
                    <th>Fee Type</th>
                    <th>Amount</th>
                    <th>Session</th>
                    <th>Is Activated</th>
                </tr>
            </thead>
            <tbody style="color:black;">
                @{int N = 0; }
            @foreach (var item in Model)
             {

                <tr>
                    @{ N += 1; }
                    <td>@N</td>
                    <td>@Html.DisplayTextFor(model => item.FeeType)</td>
                    <td>@Html.DisplayTextFor(model => item.Amount)</td>
                    <td>@Html.DisplayTextFor(model => item.Session)</td>
                    <td>
                        @if (item.IsActivated)
                        {
                            <input type="checkbox" value="@item.IsActivated.ToString()" checked onclick="ToggleFeeStatus(@item.FeeSetupId, @item.IsActivated.ToString().ToLower())"/>
                        }
                        else
                        {
                            <input type="checkbox" value="@item.IsActivated.ToString()" onclick="ToggleFeeStatus(@item.FeeSetupId, @item.IsActivated.ToString().ToLower())"/>
                        }
                    </td>
                </tr>
             }
           </tbody>
        </table>
        </div>
    </div>
}
else
{
    <div class="card">
        <div class="card-body default-section text-center">
            <i class="fa fa-trash fa-10x text-danger"></i>
            <h3 class="text-danger">No Fee Details Can be displayed at this time</h3>
        </div>
    </div>
}

<script type="text/javascript">
    function ToggleFeeStatus(feeDetailId, status) {

        $.ajax({
                type: 'POST',
                dataType: "json",
                url: '@Url.Action("ModifyFeeDetail", "AdminHome")',
                //traditional: true,
                data: { FeeDetailId: feeDetailId, FeeDetailStatus: status },
                success: function (response) {
                    console.log(response);
                },
                error: function (error) {
                    console.error(error);
                }
            });
    }
</script>

TranscriptApp.Web/Areas/Admin/Views/AdminHome/ViewTranscriptRequests.cshtml
@model IEnumerable<TranscriptApp.Web.Areas.Admin.Models.ViewTranscriptRequestsViewModel>

@{
    ViewBag.Title = "ViewTranscriptRequests";
}

<link href="~/Content/DataTables-1.10.15/media/css/jquery.dataTables.css" rel="stylesheet" />
<link href="~/Content/DataTables-1.10.15/extensions/Buttons/css/buttons.dataTables.css" rel="stylesheet" />


<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/dataTables.js"></script>
<script src="~/Content/DataTables-1.10.15/media/js/jquery.dataTables.js"></script>
<script src="~/Content/DataTables-1.10.15/extensions/Buttons/js/dataTables.buttons.js"></script>
<script src="~/Content/DataTables-1.10.15/extensions/Buttons/js/buttons.colVis.js"></script>
<script src="~/Content/DataTables-1.10.15/extensions/Responsive/js/dataTables.responsive.js"></script>
<script src="~/Content/DataTables-1.10.15/buttons.flash.min.js"></script>
<script src="~/Content/DataTables-1.10.15/buttons.html5.min.js"></script>
<script src="~/Content/DataTables-1.10.15/buttons.print.min.js"></script>
<script src="~/Content/DataTables-1.10.15/jszip.min.js"></script>
<script src="~/Content/DataTables-1.10.15/pdfmake.min.js"></script>
<script src="~/Content/DataTables-1.10.15/vfs_fonts.js"></script>


<script type="text/javascript">
    let jqXHRData;
    let jqueryVersion = $.noConflict(true);
    jqueryVersion(document).ready(() => {
        jqueryVersion("#myTable").DataTable({
            dom: 'Bfrtip',
            ordering: true,
            buttons: [
                {
                    extend: 'copy',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'csv',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'excel',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'pdf',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'print',
                    exportOptions: {
                        columns: ':visible'
                    }


                }, , 'colvis'
            ]
        });

    });
</script>

@if (Model != null && Model.Count() > 0)
{
    <div class="card">
        <div class="card-header">
            <h2>View Transcript Requests</h2>
        </div>
        <div class="card-body"  style="overflow-x: scroll;">
            <table class="table table-bordered table-hover table-striped" id="myTable">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Full Name</th>
                        <th>Email</th>
                        <th>Phone Number</th>
                        <th>Gender</th>
                        <th>Level</th>
                        <th>Programme</th>
                        <th>Department</th>
                        <th>Fee Type</th>
                        <th>Destination Address</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody style="color:black;">
                    @{int N = 0; }
                    @foreach (var item in Model)
            {

                <tr>
                    @{ N += 1; }
                    <td>@N</td>
                    <td>@Html.DisplayTextFor(model => item.FullName)</td>
                    <td>@Html.DisplayTextFor(model => item.Email)</td>
                    <td>@Html.DisplayTextFor(model => item.PhoneNumber)</td>
                    <td>@Html.DisplayTextFor(model => item.Gender)</td>
                    <td>@Html.DisplayTextFor(model => item.Level)</td>
                    <td>@Html.DisplayTextFor(model => item.Programme)</td>
                    <td>@Html.DisplayTextFor(model => item.Department)</td>
                    <td>@Html.DisplayTextFor(model => item.FeeType)</td>
                    <td>@Html.DisplayTextFor(model => item.DestinationAddress)</td>
                </tr>
    }
                </tbody>
            </table>
        </div>
    </div>
}
else
{
    <div class="card">
        <div class="card-body default-section text-center">
            <i class="fa fa-trash fa-10x text-danger"></i>
            <h3 class="text-danger">No Trasncript Requests Can be displayed at this time</h3>
        </div>
    </div>
}